### ISSUE TITLE
angular-help-overlay

### ISSUE THREAD

**Issue by Chaitanya10** [jordanburke/angular-help-overlay#1]
I'm new to angular and trying to implement angular-help-overlay in my website. but unable to make it work. no errors in debug window. i request you to provide a github working sample link for better understanding for new angularjs members like me. Thank you

**Comment by jordanburke** [comment]
Hi @Chaitanya10 have you tried the example included in this repo?

https://github.com/jordanburke/angular-help-overlay/blob/master/example/index.html
