### ISSUE TITLE
Angular 1.3 compatibility 

### ISSUE THREAD

**Issue by santimacia** [jordanburke/angular-help-overlay#2]
I tried to use this module with angular 1.3 or 1.4 but its broken.

```
[$compile:multidir] Multiple directives [ngController, helpOverlay] asking for new/isolated scope on: <body ng-controller="MainCtrl" help-overlay="showHelp" overlay-start-callback="onStart(event)" overlay-stop-callback="onStop(event)">
http://errors.angularjs.org/1.3.10/$compile/multidir?p0=ngController&p1=hel…ck%3D%22onStart(event)%22%20overlay-stop-callback%3D%22onStop(event)%22%3E
    at REGEX_STRING_REGEXP (angular.js:63)
    at assertNoDuplicate (angular.js:7994)
    at applyDirectivesToNode (angular.js:7324)
    at compileNodes (angular.js:6997)
    at compileNodes (angular.js:7009)
    at compile (angular.js:6904)
    at angular.js:1451
    at Scope.$get.Scope.$eval (angular.js:14388)
    at Scope.$get.Scope.$apply (angular.js:14487)
    at bootstrapApply (angular.js:1449)
```

**Comment by jordanburke** [comment]
Are you sure it's not because you're using two directives that are both defining scopes on the body (i.e., same) element? Try removing the ngController MainCtr and see if works.

It looks like it's more that, than 1.3/1.4 issue. Unless you already tested it in 1.2 and worked there.

Let me know!

**Comment by santimacia** [comment]
I used the example. If I move the help overlay away from the controller works, but should be on the whole body.

```
<body ng-controller="MainCtrl">
    <div class="container"  help-overlay="showHelp" overlay-start-callback="onStart(event)" overlay-stop-callback="onStop(event)">
```

**Comment by jordanburke** [comment]
Haha, a victim of my own demo. I'll take a look tonight. Thanks.

**Comment by santimacia** [comment]
Thanks, another small issue, if you initialise the help variable with true nothing happens

**Comment by jordanburke** [comment]
I cannot recall how this demo used to work in 1.2, as the 1.3/1.4 indicates a scope conflict that should not have worked back then.

In production I did not run into this issue by not having another scope on the body element and just tie it to a $root variable that another controller controls. For example:

`<body help-overlay="$root.showHelp">`

Doing something like that will allow it work right now as long you use another controller change the rootScope variable (and don't have another scope bound to the body element).

That said, for a more permanent fix, the best thing I can think of is to remove the isolate scope from this directive as it is really not essential for it to work. We can just use the link function and evaluate the attrs to get the data it needs. I'll try to check in a fix later this week.

**Comment by santimacia** [comment]
I see, that could work.

**Comment by jordanburke** [comment]
Explored not using an isolate scope, too many issues dealing with updating attributes. I left the module using it's own isolate and instead fixed the example to use a wrapper div in case someone cannot use the body element.
