### ISSUE TITLE
Invoking element using JQuery

### ISSUE THREAD

**Issue by hcbelias** [jordanburke/angular-help-overlay#3]
I`m having an issue that chardinJs function is undefined. I did a small test, trying to invoke the function using the JQuery selector($(element) besides of element) and it worked.

I would like to create a pull request, can you grant me permission?

scope.$watch('helpOverlay', function (newValue, oldValue) {
        if (newValue !== oldValue) {
          if (noop === true) {
            noop = false;
          } else if (newValue === true) {
==>>>            $(element).chardinJs('start');
          } else if (newValue === false) {
==>>>                      $(element).chardinJs('stop');
          }
        }
      });

**Comment by jordanburke** [comment]
@hcbelias thanks for the info. I'm curious under what conditions would this occur? Do you have a sample test I can see?

**Comment by MartinSeeler** [comment]
I get the same error, but was not able to fix it.

**Comment by hcbelias** [comment]
this is a MEAN app(Mongo/Express/Angular/Node) and I just added the
attribute to display the overlay help.

It looks like that the element reference that we get in the function is the
very basic element from the DOM, not the document obtained from JQuery.

2015-08-19 9:28 GMT-03:00 Martin Seeler notifications@github.com:

**Comment by jordanburke** [comment]
Alright, still haven't seen it but I'm not using the MEAN stack so perhaps that's it. Pardon the delay - It's been merged, and thanks for providing the fix.
