### ISSUE TITLE
Start/stop callbacks not correctly named in documentation

### ISSUE THREAD

**Issue by kmfreas** [jordanburke/angular-help-overlay#6]
Hi,

In the readme, the callbacks are named "help-overlay-start" and "help-overlay-stop", which don't appear to work when using them.  I checked the example [index.html](https://github.com/jordanburke/angular-help-overlay/blob/master/example/index.html) and they're used as "overlay-start-callback" "overlay-stop-callback".  Just thought you and other users should know they're named differently and that the readme should be updated.

Thanks for the code, it works pretty well!

**Comment by jordanburke** [comment]
I think I changed the names early on and must have never made the doc change, thank you for bringing it up!

Thanks I appreciate it!
